### ISSUE TITLE
figure out what to do with bibliography

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/math#4]
It seems hard to integrate `jekyll-scholar` properly, because i kind of want the "cited references" to bubble upward.

**Comment by paolobrasolin** [comment]
I think problem here is with the approach of nesting nodes via a liquid tag (`ImportTag` in your case).
That implies that:
* either you embed an already rendered node making it impossible to bubble up contextual information generated by tags like `cite`,
* or you embed an unrendered node in the hope of letting the parent node render the tags in the code of the child, but that's impossible too because you're already in the middle of rendering the parent and a second pass is not viable.

Manually handling the logic to bubble up information might be doable, but that would need to be done for every new plugin.

I think an easier solution would be using some hooks to embed the subnodes correctly before the render pass even happens. That should make any plugin work for free!

I'll give that a try and report back here, @jonsterling.

**Comment by jonsterling** [comment]
@paolobrasolin Awesome thank you!

**Comment by paolobrasolin** [comment]
Ok @jonsterling, I think I pulled it off: see PR https://github.com/jonsterling/math/pull/5.
That's basically a complete rewrite :grin: but I think it's a bit simpler and general enough for our needs.
I left a few TODOs around but none should bother you in your use case.

I took the liberty of adding the `bibliography` to the layout and the references are bubbling up as we hoped for. :confetti_ball: 

Btw, I think that with some more polishing it'd be worth packaging this a "stacks-like" Jekyll plugin for others to use!
Would it be ok with you if I did that?

Also: what other features do you think it'd be nice to have in order to consider this as a worthy alternative to gerby? :thinking:

**Comment by jonsterling** [comment]
I love it!! And it would be great to publish this as a package so that people can use it! We can Let One Hundred Flower Bloom, as it were...

**Comment by jonsterling** [comment]
Resolved by #5
